version: "3.7"
services: 
    customer-service:
        build:
            context: ./customer-service
            dockerfile: src/main/docker/Dockerfile.jvm
        ports:
            - "8080:8080"
        # depends_on:
        #     - postgres

    order-service: 
        build:
            context: ./order-service
            dockerfile: src/main/docker/Dockerfile.jvm
        ports:
            - "8081:8081"
        # depends_on:
        #     - postgres

    product-service:
        build:
            context: ./product-service
            dockerfile: src/main/docker/Dockerfile.jvm
        ports:
            - "8082:8082"
        depends_on:
            - postgres

    shopping-cart-service:
        build:
            context: ./shopping-cart-service
            dockerfile: src/main/docker/Dockerfile.jvm
        ports:
            - "8083:8083"
        # depends_on:
        #     - postgres

    postgres:
        image: postgres:14.0
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pass
        volumes:
            - ${HOME}/postgres-data/:/var/lib/postgresql/data:Z
