{
 "title": "Bare-w-beer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Earnings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application_cz_muni_fi_pv217_barewbeer_OrderResource_earnings_czk"
    }
   ]
  },
  {
   "title": "Active orders",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "application_cz_muni_fi_pv217_barewbeer_OrderResource_activeOrders_amount"
    }
   ]
  },
  {
   "title": "Customers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_cz_muni_fi_pv217_barewbeer_CustomerResource_customersCount_total"
    }
   ]
  },
  {
   "title": "Products count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_cz_muni_fi_pv217_barewbeer_ProductResource_productCount_total"
    }
   ]
  },
  {
   "title": "Shipped beers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "application_cz_muni_fi_pv217_barewbeer_OrderResource_shippedBeers_amount"
    }
   ]
  }
 ]
}